//! 〔DUP1 · 第四波 4D〕**标识符放行判定的生成物与共用金样**。
//!
//! 守的要求（逐字）：
//! - 主会话 09-26 交接（TL3 三格之①）：「**模型名**字符集 …… 定一个两侧同一份的规则（住共享 crate），真实模型名都放行。」
//! - `设计/90 §3` 判据 2：「凡是有对应 `*-core` crate 的判定，TS 侧零实现」—— 前端要在写入点先说一句的那一格，
//!   **不手抄规则**，读 monitor 从 `shell-quote-core` 那组常量现生成的 `src/generated/judgment-rules.ts`（`DUP1.md §4 ①` 的甲）。
//! - `INVARIANTS §47` ①「字符集白名单（闭集，默认拒）＋ 不许 `-` 开头（选项注入）＋ 有长度上界的就钉上界」。
//!
//! 两件事：
//! 1. [`export_bindings_judgment_rules`]：`npm run gen:types`（= `cargo test --lib export_bindings`）重写生成物；
//!    门禁第六格 `generated` 的 `git diff --exit-code` 盖住它 ⇒ 改了规则不重跑生成就红。
//! 2. [`the_shared_golden_agrees_with_the_one_rule`]：共用金样 `tests/__fixtures__/identifier-rules.golden.json`
//!    的每一条都喂给 Rust 那一份（`session_id_ok` · `model_name_ok` · `account_name_ok`），期望是金样里**手写**的；
//!    TS 那一侧 `tests/identifier-rules-parity.vitest.ts` 拿同一份金样喂生成出来的式子 ⇒ 两侧逐条对同一份，不是彼此对拍。
//!
//! 买不到：生成出来的正则与 Rust 那几行 `chars().all(...)` 是**两种写法**（一个是式子、一个是循环）——
//! 两者一致只由金样里的那些样本证明，样本之外的串（例如非 ASCII 的奇怪码位）靠两侧都「只认 ASCII」这个共同的写法兜着。

use shell_quote_core::{MODEL_NAME_EXTRA, MODEL_NAME_MAX};

/// 生成物的头。`generated-boundary-guard.vitest.ts` 认两样东西：「谁生成的」那一行 ＋「不许手改」那句话。
const HEADER: &str = "\
// 本文件由 `src/bridge/src/backend/control/payload.rs` 的
// `export_bindings_judgment_rules` 生成（`npm run gen:types`）。Do not edit this file manually.
//
// 〔DUP1〕`INVARIANTS §47` ① 标识符类的放行判定只有一份，住 `shell-quote-core`；前端要在写入点先说一句的那几条，
// 规则从那里的常量现生成到这里（不手抄）。两侧由共用金样 `tests/__fixtures__/identifier-rules.golden.json` 逐条对。
";

/// 正则字符类里要转义的那几个（其余标点在字符类里就是字面量）。
fn class_escape(c: char) -> String {
    if matches!(c, '\\' | ']' | '[' | '^' | '-' | '/') {
        format!("\\{c}")
    } else {
        c.to_string()
    }
}

/// 模型名的式子：首字符字母数字 ＋ 其余字母数字或 [`MODEL_NAME_EXTRA`] ＋ 总长 ≤ [`MODEL_NAME_MAX`]。
fn model_name_pattern() -> String {
    let extra: String = MODEL_NAME_EXTRA.chars().map(class_escape).collect();
    format!(
        "^[A-Za-z0-9][A-Za-z0-9{extra}]{{0,{}}}$",
        MODEL_NAME_MAX - 1
    )
}

fn render_judgment_rules() -> String {
    let pat = serde_json::to_string(&model_name_pattern()).expect("字符串序列化不会失败");
    let mut s = String::from(HEADER);
    s.push_str(
        "\n/** 模型名（`ANTHROPIC_MODEL` · `--model`）能不能交出去 —— 规则住 `shell_quote_core::model_name_ok`。 */\n",
    );
    s.push_str(&format!("export const MODEL_NAME_PATTERN = {pat};\n"));
    s.push_str(&format!(
        "export const MODEL_NAME_MAX = {MODEL_NAME_MAX};\n\n"
    ));
    s.push_str("const MODEL_NAME_RE = new RegExp(MODEL_NAME_PATTERN);\n\n");
    s.push_str("/** 见 [`MODEL_NAME_PATTERN`]。 */\n");
    s.push_str(
        "export function modelNameOk(s: string): boolean {\n  return MODEL_NAME_RE.test(s);\n}\n",
    );
    s
}

/// 生成 `src/generated/judgment-rules.ts`。
#[test]
fn export_bindings_judgment_rules() {
    let repo = crate::guard_support::repo_root();
    let out = repo.join("src/generated/judgment-rules.ts");
    std::fs::write(&out, render_judgment_rules())
        .unwrap_or_else(|e| panic!("写不进 {}：{e}", out.display()));
}

/// 金样逐条：Rust 那一份（三条）的判定 == 金样里手写的期望（两向：ok 全过、bad 全拒），外加反空真。
#[test]
fn the_shared_golden_agrees_with_the_one_rule() {
    let raw = include_str!("../../../__fixtures__/identifier-rules.golden.json");
    let g: serde_json::Value = serde_json::from_str(raw).expect("金样不是合法 JSON");
    let rules: [(&str, fn(&str) -> bool); 3] = [
        ("session_id", shell_quote_core::session_id_ok),
        ("model_name", shell_quote_core::model_name_ok),
        ("account_name", shell_quote_core::account_name_ok),
    ];
    let mut wrong = Vec::new();
    let mut seen = 0usize;
    for (key, ok_fn) in rules {
        for (verdict, want) in [("ok", true), ("bad", false)] {
            let list = g[key][verdict]
                .as_array()
                .unwrap_or_else(|| panic!("金样缺 {key}.{verdict}"));
            assert!(
                !list.is_empty(),
                "金样 {key}.{verdict} 是空的 —— 下面零命中地绿"
            );
            for v in list {
                let s = v.as_str().expect("样本是字符串");
                seen += 1;
                if ok_fn(s) != want {
                    wrong.push(format!("{key}：{s:?} 期望 {verdict}"));
                }
            }
        }
    }
    assert!(seen > 30, "金样只有 {seen} 条 —— 读坏了");
    assert_eq!(wrong, Vec::<String>::new(), "Rust 那一份与共用金样对不上");
}

/// 生成物里的那一份 == 从常量现算的（改了常量不重跑 `npm run gen:types` ⇒ 红，门禁第六格之外的第二道）。
#[test]
fn the_generated_file_is_what_the_constants_say() {
    let repo = crate::guard_support::repo_root();
    let on_disk = std::fs::read_to_string(repo.join("src/generated/judgment-rules.ts"))
        .expect("读不到生成物 —— 跑 npm run gen:types");
    assert_eq!(
        on_disk,
        render_judgment_rules(),
        "生成物陈旧：跑 npm run gen:types"
    );
}
