//! 〔DUP1 · 第四波 4D〕**标识符放行判定的生成物与共用金样**。
//!
//! 守的要求（逐字）：
//! - 主会话 09-26 交接（TL3 三格之①）：「**模型名**字符集 …… 定一个两侧同一份的规则（住共享 crate），真实模型名都放行。」
//! - `设计/90 §3` 判据 2：「凡是有对应 `*-core` crate 的判定，TS 侧零实现」—— 前端要在写入点先说一句的那一格，
//!   **不手抄规则**，读 monitor 从 `shell-quote-core` 那组常量现生成的 `src/generated/judgment-rules.ts`（`DUP1.md §4 ①` 的甲）。
//! - `INVARIANTS §47` ①「字符集白名单（闭集，默认拒）＋ 不许 `-` 开头（选项注入）＋ 有长度上界的就钉上界」。
//!
//! 〔DUP2 · 第四波 4D〕同一份生成物又多三样：账号名（J18，`shell_quote_core::account_name_ok` 那组常量）·
//! 账号种类取值集（J16，`acct_core::AUTH_KINDS`）· 启动期令牌的字母表与长度（J8，〔DUP3〕`shell_quote_core` 那两个常量）。
//!
//! 两件事：
//! 1. [`export_bindings_judgment_rules`]：`npm run gen:types`（= `cargo test --lib export_bindings`）重写生成物；
//!    门禁第六格 `generated` 的 `git diff --exit-code` 盖住它 ⇒ 改了规则不重跑生成就红。
//!    ⚠ 刻意**没有**「盘上那份 == 现算的」那条读回判据：同一趟 `cargo test` 里生成器与它并行跑，读到的可能是写到一半的文件
//!    （死值验时实测到生成器先把刀后的式子写了回去）—— 「生成物不陈旧」只交给门禁那一格的 `git diff`。
//! 2. [`the_shared_golden_agrees_with_the_one_rule`]：共用金样 `tests/__fixtures__/identifier-rules.golden.json`
//!    的每一条都喂给 Rust 那一份（`session_id_ok` · `model_name_ok` · `account_name_ok`），期望是金样里**手写**的；
//!    TS 那一侧 `tests/identifier-rules-parity.vitest.ts` 拿同一份金样喂生成出来的式子 ⇒ 两侧逐条对同一份，不是彼此对拍。
//!
//! 买不到：生成出来的正则与 Rust 那几行 `chars().all(...)` 是**两种写法**（一个是式子、一个是循环）——
//! 两者一致只由金样里的那些样本证明，样本之外的串（例如非 ASCII 的奇怪码位）靠两侧都「只认 ASCII」这个共同的写法兜着。

use shell_quote_core::{ACCOUNT_NAME_EXTRA, ACCOUNT_NAME_MAX, MODEL_NAME_EXTRA, MODEL_NAME_MAX};

/// 生成物的头。`generated-boundary-guard.vitest.ts` 认两样东西：「谁生成的」那一行 ＋「不许手改」那句话。
const HEADER: &str = "\
// 本文件由 `src/bridge/src/backend/control/payload.rs` 的
// `export_bindings_judgment_rules` 生成（`npm run gen:types`）。Do not edit this file manually.
//
// 〔DUP1 · DUP2〕判定只有一个家（住共享 crate，或 monitor 的渲染模块）；前端要在写入点先说一句、或要按规则造一个值的那几条，
// 规则**数据**从那里现生成到这里（不手抄）。两侧由共用金样逐条对：标识符 `tests/__fixtures__/identifier-rules.golden.json` ·
// 账号种类 `tests/__fixtures__/accounts.golden.json`；令牌由 `tests/rbind-token-shape-parity.vitest.ts` 拿铸出来的值对 Rust 源码。
";

/// 正则字符类里要转义的那几个（其余标点在字符类里就是字面量）。
fn class_escape(c: char) -> String {
    if matches!(c, '\\' | ']' | '[' | '^' | '-' | '/') {
        format!("\\{c}")
    } else {
        c.to_string()
    }
}

/// 「首字符字母数字 ＋ 其余字母数字或 `extra` ＋ 总长 ≤ `max`」那一形的式子（§47 ① 标识符那一层共用这一形）。
fn identifier_pattern(extra: &str, max: usize) -> String {
    let extra: String = extra.chars().map(class_escape).collect();
    format!("^[A-Za-z0-9][A-Za-z0-9{extra}]{{0,{}}}$", max - 1)
}

/// 模型名的式子：首字符字母数字 ＋ 其余字母数字或 [`MODEL_NAME_EXTRA`] ＋ 总长 ≤ [`MODEL_NAME_MAX`]。
fn model_name_pattern() -> String {
    identifier_pattern(MODEL_NAME_EXTRA, MODEL_NAME_MAX)
}

/// 〔DUP2 · J18〕账号名的式子：首字符字母数字 ＋ 其余字母数字或 [`ACCOUNT_NAME_EXTRA`] ＋ 总长 ≤ [`ACCOUNT_NAME_MAX`]
/// （= `shell_quote_core::account_name_ok`，与建账号的工具逐字同）。
fn account_name_pattern() -> String {
    identifier_pattern(ACCOUNT_NAME_EXTRA, ACCOUNT_NAME_MAX)
}

fn render_judgment_rules() -> String {
    let pat = serde_json::to_string(&model_name_pattern()).expect("字符串序列化不会失败");
    let acct_pat = serde_json::to_string(&account_name_pattern()).expect("字符串序列化不会失败");
    let kinds = serde_json::to_string(&acct_core::AUTH_KINDS).expect("字符串序列化不会失败");
    let mut s = String::from(HEADER);
    s.push_str(
        "\n/** 模型名（`ANTHROPIC_MODEL` · `--model`）能不能交出去 —— 规则住 `shell_quote_core::model_name_ok`。 */\n",
    );
    s.push_str(&format!("export const MODEL_NAME_PATTERN = {pat};\n"));
    s.push_str(&format!(
        "export const MODEL_NAME_MAX = {MODEL_NAME_MAX};\n\n"
    ));
    s.push_str("const MODEL_NAME_RE = new RegExp(MODEL_NAME_PATTERN);\n\n");
    s.push_str("/** 见 [`MODEL_NAME_PATTERN`]。 */\n");
    s.push_str(
        "export function modelNameOk(s: string): boolean {\n  return MODEL_NAME_RE.test(s);\n}\n",
    );
    // 〔DUP2 · J18〕账号名（新建账号表单在写入点先说一句；Rust 那一份在 `ccm …` 的 `--account` 与后端 ccm argv 判）。
    s.push_str(
        "\n/** 账号名（`--account <名>`）能不能用 —— 规则住 `shell_quote_core::account_name_ok`（与建账号的工具逐字同）。 */\n",
    );
    s.push_str(&format!(
        "export const ACCOUNT_NAME_PATTERN = {acct_pat};\n"
    ));
    s.push_str(&format!(
        "export const ACCOUNT_NAME_MAX = {ACCOUNT_NAME_MAX};\n\n"
    ));
    s.push_str("const ACCOUNT_NAME_RE = new RegExp(ACCOUNT_NAME_PATTERN);\n\n");
    s.push_str("/** 见 [`ACCOUNT_NAME_PATTERN`]。 */\n");
    s.push_str(
        "export function accountNameOk(s: string): boolean {\n  return ACCOUNT_NAME_RE.test(s);\n}\n",
    );
    // 〔DUP2 · J16〕账号种类的取值集（收成品时的白名单；`AuthKind` 这个类型也从它派生，不再手写字面量）。
    s.push_str("\n/** 账号种类的取值集 —— 契约常量住 `acct_core::AUTH_KINDS`。 */\n");
    s.push_str(&format!("export const AUTH_KINDS = {kinds} as const;\n"));
    s.push_str("/** 见 [`AUTH_KINDS`]。 */\n");
    s.push_str("export type AuthKind = (typeof AUTH_KINDS)[number];\n");
    // 〔DUP2 · J8〕启动期令牌：前端铸币口按字母表与长度**造**（构造上造不出坏形状），不再自己写一份形状再自检。
    // 〔DUP3〕两个常量与形状判定住共享 crate（`shell_quote_core::rbind_token_ok`，两半同一份）。
    let alphabet = serde_json::to_string(shell_quote_core::RBIND_TOKEN_ALPHABET)
        .expect("字符串序列化不会失败");
    s.push_str(
        "\n/** 启动期令牌的字母表与长度 —— 形状住 `shell_quote_core::rbind_token_ok`（铸币口按它们造）。 */\n",
    );
    s.push_str(&format!(
        "export const RBIND_TOKEN_ALPHABET = {alphabet};\n"
    ));
    s.push_str(&format!(
        "export const RBIND_TOKEN_LEN = {};\n",
        shell_quote_core::RBIND_TOKEN_LEN
    ));
    // 〔DUP3 · J9〕上游 base URL：新建 API 号表单逐字那一句读它（`checkBaseUrl` 只剩「空 ⇒ 默认」与「按 code 说哪句」）。
    let table = base_url_issue_patterns();
    let pats: Vec<[&str; 2]> = table.iter().map(|(c, p)| [*c, p.as_str()]).collect();
    let pats = serde_json::to_string(&pats).expect("字符串序列化不会失败");
    s.push_str(
        "\n/** 上游 base URL 用不用得了 —— 规则住 `upstream_url_core::usable`。有序表：第一条命中的就是理由，都不命中 = 能用。 */\n",
    );
    s.push_str(&format!(
        "export const BASE_URL_ISSUE_PATTERNS = {pats} as const;\n"
    ));
    s.push_str("/** 见 [`BASE_URL_ISSUE_PATTERNS`]。 */\n");
    s.push_str("export type BaseUrlIssue = (typeof BASE_URL_ISSUE_PATTERNS)[number][0];\n\n");
    s.push_str(
        "const BASE_URL_ISSUE_RES = BASE_URL_ISSUE_PATTERNS.map(([c, p]) => [c, new RegExp(p)] as const);\n\n",
    );
    s.push_str(
        "/** 见 [`BASE_URL_ISSUE_PATTERNS`]（调用方先 trim；空串 = 用默认上游，不在这里）。 */\n",
    );
    s.push_str(
        "export function baseUrlIssue(s: string): BaseUrlIssue | null {\n  for (const [c, re] of BASE_URL_ISSUE_RES) if (re.test(s)) return c;\n  return null;\n}\n",
    );
    s
}

// ─── 〔DUP3 · J9〕上游 base URL 能不能用（`upstream_url_core::usable`）的式子 ────────────────────────────
// 有序表：每条「假定前面各条都没命中」，与 `parse` / `usable` 的检查顺序一一对应；数据（空白字符全集 · 协议闭集 ·
// 端口上界 · 回环名）从 core / 标准库现取。IPv4 / IPv6 回环的写法按标准库解析器的语法生成（`127/8` · 值 == `::1`）。

/// 正则里的元字符 ⇒ 转义（字面量用）。
fn re_escape(s: &str) -> String {
    s.chars()
        .map(|c| {
            if "\\^$.|?*+()[]{}/".contains(c) {
                format!("\\{c}")
            } else {
                c.to_string()
            }
        })
        .collect()
}

/// `char::is_whitespace` 的全集（在全部标量上现枚举）⇒ 字符类。
fn whitespace_class() -> String {
    let mut s = String::from("[");
    for u in 0u32..=0x10FFFF {
        if char::from_u32(u).is_some_and(char::is_whitespace) {
            assert!(u <= 0xFFFF, "BMP 之外出现了空白字符 —— 式子得带 u 旗");
            s.push_str(&format!("\\u{u:04X}"));
        }
    }
    s.push(']');
    s
}

/// 「≤ `max` 的十进制，可带 `+`、可带前导 0」—— `u16::from_str` 的口径（端口那一格）。
fn decimal_at_most(max: u32) -> String {
    let d: Vec<u32> = max
        .to_string()
        .chars()
        .map(|c| c.to_digit(10).expect("十进制"))
        .collect();
    let n = d.len();
    let mut alts = vec![format!("[0-9]{{1,{}}}", n - 1)];
    for i in 0..n {
        if d[i] > 0 {
            let prefix: String = d[..i].iter().map(|x| x.to_string()).collect();
            let rest = n - i - 1;
            let tail = if rest > 0 {
                format!("[0-9]{{{rest}}}")
            } else {
                String::new()
            };
            alts.push(format!("{prefix}[0-{}]{tail}", d[i] - 1));
        }
    }
    alts.push(max.to_string());
    format!("\\+?0*(?:{})", alts.join("|"))
}

/// 回环主机的写法（剥方括号之前）：`\[*` ＋ 本体 ＋ `\]*`（`upstream_is_loopback` 剥的是全部前导 `[` 与尾随 `]`）。
/// `with_v6` = 本体里有没有 IPv6 那几形（它们带 `:`，只能出现在「最后一个 `:` 之前」那一格）。
fn loopback_host(with_v6: bool) -> String {
    let name: String = upstream_url_core::LOOPBACK_NAME
        .chars()
        .map(|c| format!("[{}{}]", c.to_ascii_lowercase(), c.to_ascii_uppercase()))
        .collect();
    // `Ipv4Addr` 的口径：四段、每段 0–255、不许前导 0；`is_loopback` = 首段 127。
    let o = "(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])";
    let v4 = format!("127\\.{o}\\.{o}\\.{o}");
    let mut alts = vec![name, v4];
    if with_v6 {
        alts.push(v6_loopback());
    }
    format!("\\[*(?:{})\\]*", alts.join("|"))
}

/// IPv6 回环的写法。`Ipv6Addr` 的口径：组 = 1–4 位十六进制；`::` 至少代表一组；尾部可嵌 IPv4（占两组）；`is_loopback` = 值为 1。
fn v6_loopback() -> String {
    let (z, one, v4one) = ("0{1,4}", "0{0,3}1", "0\\.0\\.0\\.1");
    let mut v6 = vec![
        format!("(?:{z}:){{7}}{one}"),
        format!("(?:{z}:){{6}}{v4one}"),
    ];
    for h in 0..=6usize {
        let head = match h {
            0 => String::new(),
            1 => z.to_string(),
            _ => format!("{z}(?::{z}){{{}}}", h - 1),
        };
        let mut tails = vec![format!("(?:{z}:){{0,{}}}{one}", 6 - h)];
        if h <= 5 {
            tails.push(format!("(?:{z}:){{0,{}}}{v4one}", 5 - h));
        }
        v6.push(format!("{head}::(?:{})", tails.join("|")));
    }
    format!("(?:{})", v6.join("|"))
}

/// J9 的有序式子表：`[code, 式子]`。
fn base_url_issue_patterns() -> Vec<(&'static str, String)> {
    use upstream_url_core::{ShapeIssue as S, Unusable as U, SCHEMES};
    let all: Vec<String> = SCHEMES.iter().map(|(s, _)| re_escape(s)).collect();
    let plain: Vec<String> = SCHEMES
        .iter()
        .filter(|(_, tls)| !tls)
        .map(|(s, _)| re_escape(s))
        .collect();
    let port = decimal_at_most(u32::from(u16::MAX));
    vec![
        (S::Whitespace.code(), whitespace_class()),
        (S::NotUrl.code(), "^(?![\\s\\S]*://)".to_string()),
        (
            S::BadScheme.code(),
            format!("^(?!(?:{})://)", all.join("|")),
        ),
        (S::NoHost.code(), "^[^:]*://(?:/|$)".to_string()),
        (S::HasQuery.code(), "^[^:]*://[^/]*[?#]".to_string()),
        (
            S::BadPort.code(),
            // 〔TAIL〕整段 `[…]` 不带口（`is_bracketed`）不算端口不对。
            format!("^[^:]*://(?!\\[[^\\]/]*\\](?:/|$))[^/]*:(?!{port}(?:/|$))[^:/]*(?:/|$)"),
        ),
        (S::NoHost.code(), "^[^:]*://:[^:/]*(?:/|$)".to_string()),
        (S::HasQuery.code(), "[?#]".to_string()),
        (
            S::DoubleSlash.code(),
            "^[^:]*://[^/]*//[\\s\\S]*[^/]".to_string(),
        ),
        (
            U::PlaintextOffLoopback.code(),
            format!(
                "^(?:{})://(?!(?:{}:[^:/]*|{}|\\[+{}\\])(?:/|$))",
                plain.join("|"),
                loopback_host(true),
                loopback_host(false),
                v6_loopback()
            ),
        ),
    ]
}

/// 生成 `src/generated/judgment-rules.ts`。
#[test]
fn export_bindings_judgment_rules() {
    let repo = crate::guard_support::repo_root();
    let out = repo.join("src/generated/judgment-rules.ts");
    std::fs::write(&out, render_judgment_rules())
        .unwrap_or_else(|e| panic!("写不进 {}：{e}", out.display()));
}

/// 金样逐条：Rust 那一份（三条）的判定 == 金样里手写的期望（两向：ok 全过、bad 全拒），外加反空真。
#[test]
fn the_shared_golden_agrees_with_the_one_rule() {
    let raw = include_str!("../../../__fixtures__/identifier-rules.golden.json");
    let g: serde_json::Value = serde_json::from_str(raw).expect("金样不是合法 JSON");
    let rules: [(&str, fn(&str) -> bool); 3] = [
        ("session_id", shell_quote_core::session_id_ok),
        ("model_name", shell_quote_core::model_name_ok),
        ("account_name", shell_quote_core::account_name_ok),
    ];
    let mut wrong = Vec::new();
    let mut seen = 0usize;
    for (key, ok_fn) in rules {
        for (verdict, want) in [("ok", true), ("bad", false)] {
            let list = g[key][verdict]
                .as_array()
                .unwrap_or_else(|| panic!("金样缺 {key}.{verdict}"));
            assert!(
                !list.is_empty(),
                "金样 {key}.{verdict} 是空的 —— 下面零命中地绿"
            );
            for v in list {
                let s = v.as_str().expect("样本是字符串");
                seen += 1;
                if ok_fn(s) != want {
                    wrong.push(format!("{key}：{s:?} 期望 {verdict}"));
                }
            }
        }
    }
    assert!(seen > 30, "金样只有 {seen} 条 —— 读坏了");
    assert_eq!(wrong, Vec::<String>::new(), "Rust 那一份与共用金样对不上");
}

/// 〔DUP3 · J9〕共用金样 `tests/__fixtures__/upstream-url.golden.json` 逐条：`upstream_url_core::usable` 的结论 == 手写的 want
/// （TS 那一侧 `tests/upstream-url-parity.vitest.ts` 读同一份跑生成的式子 ⇒ 两侧各对金样，不是彼此对拍）。
#[test]
fn the_upstream_url_golden_agrees_with_the_one_rule() {
    let raw = include_str!("../../../__fixtures__/upstream-url.golden.json");
    let g: serde_json::Value = serde_json::from_str(raw).expect("金样不是合法 JSON");
    let cases = g["cases"].as_array().expect("金样缺 cases");
    assert!(cases.len() > 40, "金样只有 {} 条 —— 读坏了", cases.len());
    let mut wrong = Vec::new();
    for c in cases {
        let url = c["url"].as_str().expect("url 是字符串");
        let got = upstream_url_core::usable(url)
            .err()
            .map(upstream_url_core::Unusable::code);
        if got != c["want"].as_str() {
            wrong.push(format!("{url:?}：得 {got:?}，金样 {:?}", c["want"]));
        }
    }
    assert_eq!(wrong, Vec::<String>::new(), "Rust 那一份与共用金样对不上");
}

/// ★★★ 〔US1 · 第四波 4D〕E4 ＋ E9：**monitor 生产树里零上游选择、零路由语法、零门牌字面量**。
///
/// 守的要求：B-decouple §2.1 必须拆 1（`APIKEY_TABLE_AGENT` · `AGENTS_WITH_DEFAULT_UPSTREAM` · 路由前缀 · 段闸 · 端口两边各一份）·
/// `设计/05 §14.3`「业务解释只有一个家」· `设计/20 §5` 目标「端口 · 路由渲染 · 段的字符闸收进共享 crate，一份实现两侧 use」。
///
/// 人群：`src/bridge/src/**/*.rs` 生产段（剥注释与测试段）× 下面两张表，**零命中**；
/// 正控（异源，证明尺子不瞎）：同一把尺子在后端上游选择 / 共享 crate 的生产段上**各数得到**每一样（逐名点住址）。
/// 端口与钥匙路径那两样还要求后端生产段零字面量（它们只许 `use` 共享 crate）。
#[test]
fn us1_the_monitor_holds_no_upstream_selection_and_no_route_grammar() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    // 住址按仓根写（`src/…`），搬树时跟着仓根走，不跟着本 crate 的深度走。
    let repo = crate::guard_support::repo_root();
    let read =
        |rel: &str| guard_core::production_code(&std::fs::read_to_string(repo.join(rel)).unwrap());
    // (名字, 它今天的家)
    let words: [(&str, &str); 8] = [
        (
            "APIKEY_TABLE_AGENT",
            "src/backend/accounts/upstream/mod.rs::CREDENTIALS_FILE_AGENT",
        ),
        (
            "AGENTS_WITH_DEFAULT_UPSTREAM",
            "src/backend/agents/mod.rs::default_upstreams",
        ),
        (
            "apikey_endpoint_for",
            "src/backend/accounts/upstream/endpoint.rs::decide_launch",
        ),
        (
            "relay_endpoint_for",
            "src/backend/accounts/upstream/endpoint.rs::decide_launch",
        ),
        (
            "RelayAsk",
            "src/backend/accounts/upstream/endpoint.rs::decide_launch",
        ),
        (
            "apikey_rows",
            "src/backend/accounts/upstream/file_face.rs::rows_at",
        ),
        (
            "read_accounts",
            "src/backend/accounts/upstream/file_face.rs::read_at",
        ),
        (
            "apikey_routed_subset",
            "src/backend/accounts/upstream/endpoint.rs::answer_routing_with",
        ),
    ];
    let literals: [(&str, &str); 4] = [
        ("\"/s/\"", "src/common/relay-route-core/src/lib.rs"),
        ("\"/t/\"", "src/common/relay-route-core/src/lib.rs"),
        ("8788", "src/common/relay-route-core/src/lib.rs"),
        (
            "\".cc-monitor/relay-key\"",
            "src/common/relay-route-core/src/lib.rs",
        ),
    ];
    let mut hits = Vec::new();
    for (at, src) in guard_core::scan_tree_excluding(&root.join("src"), &["rs"], &[]) {
        let prod = guard_core::production_code(&src);
        for (w, _) in words {
            if guard_core::contains_word(&prod, w) {
                hits.push(format!("{} · `{w}`", at.display()));
            }
        }
        for (l, _) in literals {
            if prod.contains(l) {
                hits.push(format!("{} · {l}", at.display()));
            }
        }
    }
    assert!(
        hits.is_empty(),
        "monitor 生产树里又长出了上游选择 / 路由语法 / 门牌字面量：\n  {}",
        hits.join("\n  ")
    );
    // 正控：家里数得到（名字那一张：家文件里那个「今天的名字」在；字面量那一张：共享 crate 里在）。
    for (w, home) in words {
        let (file, sym) = home.split_once("::").unwrap();
        assert!(
            guard_core::contains_word(&read(file), sym),
            "`{w}` 的家 {home} 里数不到 `{sym}` —— 尺子或住址坏了"
        );
    }
    for (l, home) in literals {
        assert!(
            read(home).contains(l),
            "共享 crate 里数不到 {l} —— 尺子是瞎的"
        );
    }
    // 后端那一半：端口与钥匙路径只许 `use` 共享 crate（零字面量）。
    let mut backend_hits = Vec::new();
    for (at, src) in guard_core::scan_tree_excluding(&repo.join("src/backend"), &["rs"], &[]) {
        let prod = guard_core::production_code(&src);
        for l in ["8788", "\".cc-monitor/relay-key\""] {
            if prod.contains(l) {
                backend_hits.push(format!("{} · {l}", at.display()));
            }
        }
    }
    assert!(
        backend_hits.is_empty(),
        "后端生产树里还有门牌字面量（该 use relay_route_core）：{backend_hits:?}"
    );
}
