// 由 `tests/frontend/ui/css-modules.vitest.ts` 对拍：本文件 == 从 `plan-cell.module.css` 渲染出的规范文本（逐字）。
declare const classes: {
  readonly cd: string;
  readonly cdAside: string;
  readonly cdBadge: string;
  readonly cdBar: string;
  readonly cdCounts: string;
  readonly cdCrumb: string;
  readonly cdFileState: string;
  readonly cdFold: string;
  readonly cdFoldHead: string;
  readonly cdFoldHint: string;
  readonly cdGap: string;
  readonly cdGroup: string;
  readonly cdGroupHead: string;
  readonly cdHead: string;
  readonly cdId: string;
  readonly cdKind: string;
  readonly cdKw: string;
  readonly cdLine: string;
  readonly cdLink: string;
  readonly cdMono: string;
  readonly cdMuted: string;
  readonly cdPos: string;
  readonly cdPre: string;
  readonly cdProse: string;
  readonly cdRef: string;
  readonly cdSec: string;
  readonly cdSecHead: string;
  readonly cdSign: string;
  readonly cdSignHead: string;
  readonly cdSignWhy: string;
  readonly cdSt: string;
  readonly cdTbl: string;
  readonly cdTitle: string;
  readonly cdWhy: string;
};
export default classes;
