// 由 `tests/frontend/ui/css-modules.vitest.ts` 对拍：本文件 == 从 `rules-section.module.css` 渲染出的规范文本（逐字）。
declare const classes: {
  readonly rules: string;
  readonly rulesActions: string;
  readonly rulesBatch: string;
  readonly rulesBatchN: string;
  readonly rulesBody: string;
  readonly rulesEmpty: string;
  readonly rulesFilter: string;
  readonly rulesHead: string;
  readonly rulesHeadRow: string;
  readonly rulesName: string;
  readonly rulesNameText: string;
  readonly rulesNew: string;
  readonly rulesNewFoot: string;
  readonly rulesNewRow: string;
  readonly rulesNewTitle: string;
  readonly rulesRename: string;
  readonly rulesRenameErr: string;
  readonly rulesRenameInput: string;
  readonly rulesRow: string;
  readonly rulesSp: string;
  readonly rulesSub: string;
  readonly rulesSum: string;
  readonly rulesTable: string;
  readonly rulesTitle: string;
  readonly rulesUse: string;
  readonly rulesUseBtn: string;
  readonly rulesUser: string;
  readonly rulesUserName: string;
  readonly rulesUserState: string;
  readonly rulesUsers: string;
  readonly rulesUsersFoot: string;
};
export default classes;
