//! `K-R95`（定框 `K28`：前端不许自己发明对外行为）：「要跑什么」这件事上，
//! **前端此前自己写死的那几格**改成从后端取。
//!
//! # 为什么走生成物，而不是再开一条 IPC
//!
//! 与上一件 `K-R93` 同一个理由：消费点（`launch-account.ts::localLaunchAccountSync` 的载荷键名）
//! 是**同步纯函数**，而 IPC 是异步的。⇒ 选生成物那条：
//! **同样做到「后端改一处，前端手里那份跟着变」**。
//!
//! # 今天只剩一格
//!
//! | 格 | 前端此前哪一处自己写 | 现在的源 |
//! |---|---|---|
//! | 本机拉起载荷「哪个号」那一格的 wire 键名 | `accounts.ts` 里 `{ kind: "named", configDir, name }` | [`crate::control::launch_render::local::LaunchAccount`] 的 serde 契约 |
//!
//! 原来还有两格 —— `ccm …` 调用行每次都要的能力集、八句降级理由的措辞 ——
//! 唯一的消费者是 TS 那份 `ccm …` 渲染器；它删了（生产从 U8c-2c-2 起只走 Rust），
//! 两格与它们的生成段、`KR95D3` 那句「没探出来 ≠ 没装」一起退役。
//! ⚠ 那一句**生产上本来就说不出来**：线上 `CliRenderRequest.caps` 只有两态（见
//! [`super::CliRenderRequest::caps`] 上登记的缺口 R95b）。它的下一次出生应当在修 R95b 的那一拍、
//! 住进 `ccm_invocation::Refusal`，由 Rust 判据管。
//!
//! ⚠ **这一格的诚实边界**：`LaunchAccount` 今天只派生 `Deserialize`（它是命令入参），
//! 序列化不出来 ⇒ 键名在本模块里仍是**写出来的**，但它们**每次生成都跑一遍生产
//! 反序列化器验一次**（还配了阴性对照：换一个名字必须被拒）。
//! ⇒ `history.rs` 那边改名 ⇒ `npm run gen:types` 当场 panic，而不是悄悄生成一份旧的。

/// 🔴 `K-R95`：本机拉起载荷里「哪个号」那一格的**取值口**（随下面那条判据从
/// `launch_cli_parity.rs` 搬来 —— 它与 `ccm …` 渲染器无关）。
/// 住址从 `src/frontend/ui/accounts.ts` 换到 `src/frontend/ui/launch-account.ts`：`accounts.ts` 按域拆开，
/// 「起会话挑哪个号 ＋ 载荷上那一格的形状」归起停域那一份。
const TS_ACCOUNTS: &str = include_str!("../../../../src/frontend/ui/launch-account.ts");

/// 生成物的头。`generated-boundary-guard.vitest.ts` 认两样东西：
/// 「谁生成的」那一行 ＋「不许手改」那句话。
const HEADER: &str = "\
// 本文件由 `src/backend/control/launch_render/wire.rs` 的
// `export_bindings_launch_render_facts` 生成（`npm run gen:types`）。Do not edit this file manually.
//
// `K-R95`：**「要跑什么」只有后端一份说法**（定框 `K28`：前端不许自己发明对外行为）。
// 下面每一格都是生成时**跑一遍后端生产代码现算的**，不是照抄一遍常量 ——
// 改后端那一处、跑 `npm run gen:types`，前端手里这一份就跟着变。
";

/// TS 字符串字面量。走 `serde_json` 而不是自己拼引号：转义规则一次到位，
/// 中文按原样输出（`serde_json` 不转 non-ASCII）。
fn ts_str(s: &str) -> String {
    serde_json::to_string(s).expect("字符串序列化不会失败")
}

/// 逐行追加。**刻意收一个 `&[&str]` 而不是一行一次调用**：后者里超宽的中文注释行
/// 会被 `rustfmt` 拆成三行（`line(`／`&mut s,`／字面量），而数组元素它拆不动。
fn lines(s: &mut String, ts: &[&str]) {
    for t in ts {
        s.push_str(t);
        s.push('\n');
    }
}

/// 本机拉起载荷里「哪个号」那一格的 wire 键名 —— **每次生成都跑生产反序列化器验一遍**。
///
/// 返回 `(TS 侧的键, 线上的名字)`。
fn local_launch_account_wire() -> Vec<(&'static str, &'static str)> {
    use crate::control::launch_render::local::LaunchAccount;
    let named: LaunchAccount = serde_json::from_value(serde_json::json!({
        "kind": "named", "configDir": "/d", "name": "n"
    }))
    .expect(
        "`local.rs::LaunchAccount` 不再收 `{kind:\"named\", configDir, name}` —— \
             前端手里那份载荷键名已经过期了，先改这里的表再生成",
    );
    match &named {
        LaunchAccount::Named { config_dir, name } => {
            assert_eq!(config_dir, "/d", "`configDir` 没落进 `config_dir`");
            assert_eq!(
                name.as_deref(),
                Some("n"),
                "`name` 没落进 `name` —— 它有 `#[serde(default)]`，改名不会报缺字段，\
                     只会**静默变 None**（= 那次拉起从此进不了 ccm 容器）。本条就是为它写的"
            );
        }
        other => panic!("`kind:\"named\"` 解出来不是 `Named`：{other:?}"),
    }
    let base: LaunchAccount = serde_json::from_value(serde_json::json!({ "kind": "base" }))
        .expect("`local.rs::LaunchAccount` 不再收 `{kind:\"base\"}`");
    assert!(
        matches!(&base, LaunchAccount::Base),
        "`kind:\"base\"` 解出来不是 `Base`：{base:?}"
    );
    // ★ 阴性对照：上面两条若因为「反序列化太宽」而恒真，这一条会揭穿它。
    assert!(
        serde_json::from_value::<LaunchAccount>(serde_json::json!({
            "kind": "named", "cfgDir": "/d"
        }))
        .is_err(),
        "换个键名照样收 ⇒ 上面那两条是恒真的，这张表此刻没人管"
    );
    vec![
        ("tag", "kind"),
        ("named", "named"),
        ("base", "base"),
        ("configDir", "configDir"),
        ("name", "name"),
    ]
}

/// 生成 `src/frontend/ui/generated/launch-render-facts.ts` 的正文。
fn render_launch_render_facts() -> String {
    let mut s = String::from(HEADER);

    lines(
        &mut s,
        &[
            "",
            "/**",
            " * 本机拉起载荷里「哪个号」那一格的 **wire 键名**。",
            " *",
            " * 源：`local.rs::LaunchAccount` 的 serde 契约，生成时**跑一遍生产反序列化器**",
            " * 验过（还配了阴性对照）⇒ 那边改名，`npm run gen:types` 当场 panic。",
            " *",
            " * ⚠ 前端要**用计算键**读它，不许再把 `configDir` 这几个字自己写一遍 ——",
            " * 写了就又是第二份说法。",
            " */",
            "export const LOCAL_LAUNCH_ACCOUNT_WIRE = {",
        ],
    );
    for (key, wire) in local_launch_account_wire() {
        lines(&mut s, &[&format!("  {key}: {},", ts_str(wire))]);
    }
    lines(&mut s, &["} as const;"]);
    s
}

/// `K-R95`：生成 `src/frontend/ui/generated/launch-render-facts.ts`。
///
/// 名字必须以 `export_bindings` 打头 —— `npm run gen:types` 就是
/// `cargo test --lib export_bindings`。
#[test]
fn export_bindings_launch_render_facts() {
    let repo = crate::guard_support::repo_root();
    let out = repo.join("src/frontend/ui/generated/launch-render-facts.ts");
    let body = render_launch_render_facts();
    std::fs::write(&out, body).unwrap_or_else(|e| panic!("写不进 {}：{e}", out.display()));
}

/// ★★ 🔴 `KR95D1`：生成物里那一格**真的是跑后端算出来的**，不是一份写死的表。
///
/// 本条查的是**产出**：拿后端此刻验过的值现算一遍，与写进生成物的那份逐字节比。
/// ⇒ 改后端一处而没跑 `npm run gen:types` ⇒ 门禁第六格 `generated` 的 `git diff` 红。
#[test]
fn the_facts_the_frontend_holds_are_recomputed_from_the_backend_every_time() {
    let body = render_launch_render_facts();
    for (key, wire) in local_launch_account_wire() {
        assert!(
            body.contains(&format!("  {key}: {},", ts_str(wire))),
            "wire 键名 {key} 没进生成物（后端验过的是 {wire:?}）"
        );
    }
    // 反向自检：随便编一个后端说不出的值，必须**不在**里面（否则上面几条恒真）。
    assert!(
        !body.contains("\"没有人说过这句话\""),
        "生成物里出现了后端说不出的值 —— 上面那几条此刻恒真"
    );
    // 退役的两格不许回来（它们没有消费者了）。
    for gone in ["CLI_REQUIRED_CAPS", "CLI_REFUSAL_REASON"] {
        assert!(
            !body.contains(gone),
            "生成物里又出现了 `{gone}` —— 它唯一的消费者（TS 那份 `ccm …` 渲染器）已删"
        );
    }
}

/// ★★ 🔴 `K-R95` `KR95D1` **刀③**（「前端退回自己拼 ⇒ 必须红」）：
/// `launch-account.ts`（原 `accounts.ts`）真的用**计算键**读生成物那张表，而不是把三个键名再写一遍。
///
/// # ⚠ 本条是**判写法**，登记在案 —— 别把它当成 `KR95D1` 的主判据
///
/// 主判据是**产出**那一侧：`launch_wire.rs` 的
/// `the_facts_the_frontend_holds_are_recomputed_from_the_backend_every_time`
/// （拿后端此刻的值现算一遍去比生成物）＋ 门禁第六格 `generated` 的
/// `git diff --exit-code`（改后端不重生成 ⇒ 红）。
///
/// 本条只补 **刀③** 那一格，而那一格在**同步纯函数**上除了源码层没有别的抓手：
/// 前端把 `{ kind: "named", configDir, name }` 三个字面量写回去，产出与今天**逐字节相同**
/// ⇒ 任何按产出判的东西都看不见它，直到某天 `history.rs` 改名才一起爆。
/// ⇒ 判据体系里必须有一条**看得见「它是从哪儿拿的」**，代价是它按写法判。
#[test]
fn the_frontend_reads_the_account_wire_table_instead_of_writing_the_keys_out_again() {
    for needle in [
        "[LOCAL_LAUNCH_ACCOUNT_WIRE.tag]:",
        "[LOCAL_LAUNCH_ACCOUNT_WIRE.configDir]:",
        "[LOCAL_LAUNCH_ACCOUNT_WIRE.name]:",
    ] {
        assert!(
            TS_ACCOUNTS.contains(needle),
            "`src/frontend/ui/launch-account.ts` 里没有 `{needle}` —— 本机拉起载荷「哪个号」那一格\n\
                 又变回前端自己拼了（`K28`：前端不许自己发明对外行为）。\n\
                 ⚠ 产出**逐字节相同**，所以除了本条没有任何东西看得见它。"
        );
    }
}
