use super::*;

/// Phase 2 F1a：records_dir_for 按 kind 派生正确子目录（Claude=projects / Codex=sessions）。
#[test]
fn records_dir_for_per_kind() {
    let root = Path::new("/home/u/.claude");
    assert_eq!(
        records_dir_for(AgentKind::ClaudeCode, root),
        Path::new("/home/u/.claude/projects")
    );
    let croot = Path::new("/home/u/.codex");
    assert_eq!(
        records_dir_for(AgentKind::Codex, croot),
        Path::new("/home/u/.codex/sessions")
    );
}

/// enabled_kinds 恒含 Claude（零回归）；Codex 仅当 ~/.codex/sessions 存在时纳入（machine-dependent，
/// 此处只锁 Claude 恒在 + records_roots 有对应 projects 根，Codex 分支由装了 Codex 的机器真机验证）。
#[test]
fn enabled_kinds_always_includes_claude() {
    assert!(enabled_kinds().contains(&AgentKind::ClaudeCode));
    let roots = records_roots();
    let claude = roots.iter().find(|(k, _)| *k == AgentKind::ClaudeCode);
    assert!(
        claude
            .map(|(_, d)| d.ends_with("projects"))
            .unwrap_or(false),
        "Claude 根应以 projects 结尾"
    );
}

/// kind_of_path：不在任何启用 kind 根下的路径 → 默认 `ClaudeCode`（**零回归**：非 Codex 路径
/// 走原 Claude 行为；调用方仍会对该根做前缀校验挡非法路径）。真根下派发由真机集成验证。
#[test]
fn kind_of_path_defaults_to_claude_for_unrooted() {
    assert_eq!(
        kind_of_path(Path::new("/tmp/nowhere/x.jsonl")),
        AgentKind::ClaudeCode
    );
}

// ── `K-R93`：把前端那份画像**生成出去** ─────────────────────────────────
//
// `npm run gen:types` 逐字就是 `cd src/bridge && cargo test --lib export_bindings`
// ⇒ 本条会被它跑到；门禁第六格 `generated` 随后判「已提交的那份与 Rust 源一不一致」。
// ⇒ **改了上面那几张表而不重跑生成 ⇒ 门禁红**，这就是 `KR93D1` 要的那条牙。

/// 生成物的头。「Do not edit this file manually」那句话是给
/// `tests/generated-boundary-guard.vitest.ts` 那条判据看的，别改措辞。
///
/// 🔴 **本段与下面 `TABLE_HEADER_TAIL` 刻意分成两个字面量，别合回去。**
/// `guard_core::test_module_ranges` 用「**列 0 的右大括号**」判测试模块到哪儿收尾
/// （它刻意不解析字符串 / 原始字符串，理由写在那个函数自己的头注里）。
/// 这段 TS 里 `};`（`AgentProfileRow` 那个类型的收尾）一旦落在本 `.rs` 文件的列 0，
/// **测试模块就在那里被切断**，后面的测试代码全被当成生产段。
/// 〔实打，09-12 本件第一趟门禁：合成一个字面量 ⇒ `cargo` 当场**四条**红 ——
/// `structural_scan.rs`（剥完仍残留测试属性）· `write_site_registry.rs`（把生成器那句
/// `fs::write` 当成未申报的写盘落点）· `agent_dispatch_registry.rs` 两条（把测试段里的
/// agent 名数成了生产耦合点）。**四条都不是假红，是那一刀真的把模块切断了。**
/// 四条判据的逐字名字与读数住 `tests/evidence/K-R93-deathvalue.md`〕
const TABLE_HEADER: &str = r#"// 本文件由 `src/bridge/src/adapter.rs` 的 `export_bindings_agent_profile_table` 生成
// （`npm run gen:types`）。Do not edit this file manually.
//
// `K-R93`：**前端那份 agent 画像的值来自后端**（`adapter.rs::agent_profile_facts`），
// 不再是 `src/agent-profile.ts` 里自己写死的一份常量 —— 那一份只认 claude，
// 接上后端的同一刻把 codex 那一格也补上了。
//
// ⚠ **`null` ≠ 空**：`null` = 这一格今天没人考据过（后端 `None`），**不许拿 claude 那份顶上**
// （`KR93D3`）；`[]` 才是「考据过、确实是空的」。

export type AgentProfileRow = {
  /** 这张表的键（= `agent-profile-golden.tsv` 第一列，也是 `ccm --agent` 收的那个名字）。 */
  agent: string;
  /** 后端适配器 id（`AgentAdapter::id()`）。 */
  adapterId: string;
  defaultLauncher: string;
  launcherAlias: string | null;
  resumeKind: "flag" | "subcommand";
  resumeToken: string;
  nestedEnvVars: string[];
  agentTools: string[] | null;
  interactiveTools: string[] | null;
  diffTools: string[] | null;
  mdTools: string[] | null;
  livenessProcessNames: string[] | null;
"#;

/// 接着上面那一段 —— **第一行就是那个收尾的 `};`**（见上面为什么不能合并）。
const TABLE_HEADER_TAIL: &str = r#"};

export const AGENT_PROFILE_TABLE: readonly AgentProfileRow[] = [
"#;

/// `ACTIVE_AGENT` 那一格的头注（后端 `active()` 今天是谁，不是前端自己挑的）。
const ACTIVE_HEADER: &str = r#"
/** 后端 `adapter::active()` 今天派发给谁 —— `AGENT_PROFILE` 就是它那一份。 */
"#;

/// 一个 TS 串字面量。**这个生成器不做转义** —— 真出现要转义的字符就当场炸，不产坏 TS。
fn ts_str(s: &str) -> String {
    assert!(
        !s.contains('"') && !s.contains('\\'),
        "画像里出现了要转义的字符：{s:?}"
    );
    format!("\"{s}\"")
}

fn ts_list(v: &[&str]) -> String {
    let items: Vec<String> = v.iter().map(|s| ts_str(s)).collect();
    format!("[{}]", items.join(", "))
}

/// `None` ⇒ `null`（**「没人考据过」，不是空数组**）。
fn ts_opt_list(v: Option<&[&str]>) -> String {
    v.map(ts_list).unwrap_or_else(|| "null".to_string())
}

fn ts_opt_str(v: Option<&str>) -> String {
    v.map(ts_str).unwrap_or_else(|| "null".to_string())
}

fn row_fields(f: &AgentProfileFacts) -> Vec<(&'static str, String)> {
    let inter = ts_opt_list(f.interactive_tools);
    let live = ts_opt_list(f.liveness_process_names);
    vec![
        ("agent", ts_str(f.agent)),
        ("adapterId", ts_str(f.adapter_id)),
        ("defaultLauncher", ts_str(f.default_launcher)),
        ("launcherAlias", ts_opt_str(f.launcher_alias)),
        ("resumeKind", ts_str(f.resume_kind)),
        ("resumeToken", ts_str(f.resume_token)),
        ("nestedEnvVars", ts_list(f.nested_env)),
        ("agentTools", ts_opt_list(f.agent_tools)),
        ("interactiveTools", inter),
        ("diffTools", ts_opt_list(f.diff_tools)),
        ("mdTools", ts_opt_list(f.md_tools)),
        ("livenessProcessNames", live),
    ]
}

fn render_row(f: &AgentProfileFacts) -> String {
    let mut s = String::new();
    s.push_str("  {\n");
    for (key, value) in row_fields(f) {
        s.push_str("    ");
        s.push_str(key);
        s.push_str(": ");
        s.push_str(&value);
        s.push_str(",\n");
    }
    s.push_str("  },\n");
    s
}

/// 后端 [`active`] 今天是哪一个 agent（按 [`AgentAdapter::id`] 回查表键）。
fn active_agent_key() -> &'static str {
    let id = active().id();
    for kind in ALL_AGENT_KINDS {
        let f = agent_profile_facts(kind);
        if f.adapter_id == id {
            return f.agent;
        }
    }
    panic!("`active()` 的 id `{id}` 不在 ALL_AGENT_KINDS 里 —— 表漏了一个 agent");
}

fn render_agent_profile_table() -> String {
    let mut s = String::from(TABLE_HEADER);
    s.push_str(TABLE_HEADER_TAIL);
    for kind in ALL_AGENT_KINDS {
        s.push_str(&render_row(&agent_profile_facts(kind)));
    }
    s.push_str("];\n");
    s.push_str(ACTIVE_HEADER);
    s.push_str("export const ACTIVE_AGENT: string = ");
    s.push_str(&ts_str(active_agent_key()));
    s.push_str(";\n");
    s
}

/// `K-R93`：生成 `src/generated/agent-profile-table.ts`。
#[test]
fn export_bindings_agent_profile_table() {
    let repo = crate::guard_support::repo_root();
    let out = repo.join("src/generated/agent-profile-table.ts");
    let body = render_agent_profile_table();
    std::fs::write(&out, body).unwrap_or_else(|e| panic!("写不进 {}：{e}", out.display()));
}
