/**
 * C01（rust-ts-boundary）：**结构性守卫**——生成物必须存在、必须被消费、必须与 Rust 侧一致。
 *
 * **这不是行为测试，也不假装是。** C01 的行为判据是**变异**：
 * 删掉 Rust 的 `DataPathInfo.exists` → 重新导出 → `tsc` 报 6 条错（全部指向
 * `data-section.ts`）；给 `label` 加 `#[serde(rename)]` → `tsc` 报错。
 * 两次都先 `git diff` 确认变异落位、再确认 `cargo test --lib` 538 绿，**然后**才判 tsc 的色
 * ——中间踩了一次「变异编译不过、tsc 却是 0 错」，那个 0 错毫无意义
 * （生成物根本没被重新导出）。全部记在 `.claude/planned-build/rust-ts-boundary/features/C01-*.md`。
 *
 * 本文件只负责防**接线被悄悄拆掉**。**它抓不到的，见下方「本守卫的已知盲区」。**
 *
 * ## 本守卫的已知盲区（Phase D 审计实测，别在别处声称它们被守住）
 *
 * 1. **手改生成物抓不到。** 审计实测：手工把 `kind: string` 收窄成 `"file" | "dir"`、
 *    再插一个 Rust 侧根本不存在的字段 —— **5 条守卫全绿、`tsc` 全绿**。
 *    唯一能抓的是「重跑导出 + diff」，那是 **C05**。
 * 2. **「改了 Rust 但没重新生成」抓不到全部。** CI 的 `rust` job（跑 `cargo test`）与
 *    `frontend` job（跑 `tsc`）是**两次独立 checkout**，重新生成的产物在前者里被丢掉，
 *    后者对着**已提交的**生成物做类型检查。审计实测：serde-rename 一个字段而不重新生成
 *    ⇒ cargo 绿、tsc 绿、守卫绿、npm 819 全绿，**而生产里 UI 标签会变空**。
 *    下方第 4 条测试的「性质②」覆盖其中**一部分**（Rust 侧属性被撤走、而生成物还是旧的），
 *    但根治要靠 C05 的「同一棵树里先 regen 再 tsc」。
 *
 * 因此 **C05 必须早于 C02/C03/C04 落地**，否则这个洞会被复制到 127 个 struct（审计 I1）。
 */
import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const read = (p: string) => readFileSync(resolve(ROOT, p), "utf8");

/**
 * **剥注释再扫——守卫与断言两侧都要剥，Rust 侧也要剥。**
 *
 * 本文件栽过两轮：
 * ① 第一版没剥，生成物的 JSDoc 里含有我写在 Rust doc comment 里的 `sizeBytes: bigint | null`
 *    那串字，被当成类型判据；
 * ② 剥了 TS 侧、**忘了剥 Rust 侧** —— Phase D 审计变异实测：把
 *    `#[ts(optional, type = "number")]` 真的删掉、只留注释，那条「钉住显式决定」的断言
 *    **依然绿**，因为 doc comment 里就写着 `` `type = "number"` `` 这串字。
 *    这是本会话同一形状的第三次。
 *
 * Rust 与 TS 的行注释与块注释语法一致，所以这里共用一套正则。
 * （**别在这段块注释里写块注释的结束符**——第一版就是这么把注释提前关掉、
 *   让整个文件变成语法错的：注释谈注释语法，反而破坏了注释。）
 */
function code(src: string): string {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, "") // 块注释 / JSDoc
    .replace(/(^|[^:])\/\/.*$/gm, "$1"); // 行注释 + Rust doc comment（`https://` 不误伤）
}

/** ts-rs v12 写在每个生成文件头部的原话（硬编码在 ts-rs 里，改不了，所以不是 `@generated`）。 */
const TS_RS_HEADER = "generated by [ts-rs]";
const DO_NOT_EDIT = "Do not edit this file manually";

/** 今天纳入生成的 Rust 源文件。C02/C03/C04 往里加时，下方计数自检会红一次提醒。 */
const TS_DERIVING_SOURCES = ["src-tauri/src/data_paths.rs"];

describe("C01 边界生成物", () => {
  it("生成目录里只有生成物，且每个都带「不许手改」标记", () => {
    // **用 readdir 而不是写死数组**（审计 I2）：第一版遍历一个硬编码的二元字面量数组
    // 再断言 `checked === 2`，那在算术上不可能失败——注释却写着「加了第三个文件会红」。
    // 审计实测：往 `src/generated/` 塞一个连 ts-rs 头都没有的手写文件 → 5 条全绿。
    const files = readdirSync(resolve(ROOT, "src/generated")).filter((f) => f.endsWith(".ts"));
    files.sort();
    // 计数自检用等号：C02 加进新文件时这里必须红一次，提醒把它纳入下方逐项断言
    expect(files, "生成目录内容变了——把新文件纳入本守卫再更新这个期望").toEqual([
      "DataPathInfo.ts",
      "DataPathsResponse.ts",
    ]);
    for (const f of files) {
      const src = read(`src/generated/${f}`);
      expect(src.length, `${f} 是空的`).toBeGreaterThan(100);
      expect(src, `${f} 缺 ts-rs 头`).toContain(TS_RS_HEADER);
      expect(src, `${f} 缺「不许手改」`).toContain(DO_NOT_EDIT);
    }
  });

  it("camelCase 真的从 serde 属性传下来了（选 ts-rs 的前提）", () => {
    // **剥注释**（审计 I3）：第一版这两个是裸 `read`，而 `sizeBytes` 在 JSDoc 里也出现一次
    // （`formatBytes(info.sizeBytes)` 那句散文），所以正向断言在字段被改名后**依然绿**，
    // 全部承重落在 `not.toContain("size_bytes")` 上。
    const info = code(read("src/generated/DataPathInfo.ts"));
    const resp = code(read("src/generated/DataPathsResponse.ts"));
    expect(info, "剥过头了").toContain("export type DataPathInfo");
    expect(resp, "剥过头了").toContain("export type DataPathsResponse");
    expect(info).toContain("sizeBytes");
    expect(info).not.toContain("size_bytes");
    expect(resp).toContain("monitorDataDir");
    expect(resp).toContain("webviewUserDataDir");
    expect(resp).toContain("profileBackupDirs");
    expect(resp).not.toContain("monitor_data_dir");
  });

  it("每一处 skip_serializing_if 都配了 ts(optional)——通用性质，不是单字段字面量", () => {
    // **审计 S3**：第一版把这条通用性质写成了对 `sizeBytes` 一个字段的字面量断言，
    // 一到 C02 就得再抄一遍。改成扫源码：**只查带 `ts_rs::TS` 派生的 struct**
    // （没派生 TS 的 struct 不需要 `ts(optional)`，对它们要求就是假红）。
    //
    // 性质：`skip_serializing_if` ⇒ 字段在 JSON 里可缺席 ⇒ TS 侧必须是 optional。
    // 少了它，`ts-rs` 生成一个必需字段，**类型就在撒谎**。
    let checked = 0;
    for (const f of TS_DERIVING_SOURCES) {
      const src = code(read(f));
      expect(src, `${f}: 剥过头了`).toContain("pub struct");
      // 按 `#[derive` / `#[cfg_attr(test, derive` 边界切成块，只留提到 ts_rs::TS 的块
      const blocks = src.split(/(?=#\[(?:derive|cfg_attr\(test, derive))/);
      for (const b of blocks) {
        if (!b.includes("ts_rs::TS")) continue;
        for (const m of b.matchAll(/skip_serializing_if/g)) {
          const after = b.slice(m.index, m.index + 400);
          expect(
            after,
            `${f}: 有 skip_serializing_if 的字段没配 ts(optional)——生成的类型会声明一个可缺席的必需字段`,
          ).toMatch(/ts\(optional/);
          checked += 1;
        }
      }
    }
    // 反向自检 + 计数自检：今天恰好 1 处（`data_paths.rs` 的 `size_bytes`）。
    // 加了新的就必须红一次，确认新那处也配了。
    expect(checked, `期望恰好 1 处 skip_serializing_if，实得 ${checked}`).toBe(1);
  });

  it("`u64` 的映射与运行时一致，且属性真的在源码里（不是被注释喂饱）", () => {
    const info = code(read("src/generated/DataPathInfo.ts"));
    const rust = code(read("src-tauri/src/data_paths.rs")); // ← 审计 B1：这里以前是裸 read
    expect(info, "剥过头了").toContain("export type DataPathInfo");
    expect(rust, "剥过头了").toContain("pub struct DataPathInfo");

    // 性质①：类型必须与运行时一致。Tauri 命令返回值走 `serde_json::to_string`
    // （`tauri-2.11.2/src/ipc/mod.rs:181-183`，审计独立取证）⇒ 线上是 JSON 文本，
    // 而 `JSON.parse` 永不产出 BigInt ⇒ `u64` 到 TS 侧**在原理上不可能**是 bigint。
    expect(info).toContain("sizeBytes?: number");
    expect(info, "回落到 ts-rs 默认的 bigint 了——那与运行时不一致").not.toContain("bigint");

    // 性质②：那个收窄必须是**源码里真的写着的属性**，不是碰巧、也不是注释里提过。
    // **审计 B1 实测**：用裸 `read` 时把属性真的删掉、只留注释，这条依然绿。
    // 它覆盖的那一格是「改了 Rust 但没重新生成」——性质① 在那一格是绿的（生成物还是旧的）。
    expect(rust, "Rust 侧的 `type = \"number\"` 收窄不见了").toContain('type = "number"');

    // **不再断言注释里的上限论证**（审计 S2）：那是散文，有人把 `2^53-1` 重排成 `2^53 - 1`
    // 就会假红，而假红的守卫会被人关掉。论证留在 `data_paths.rs` 的注释里给人读，不做机检。
  });

  it("data-section.ts 的类型来自生成物，本地手写 interface 不许回来", () => {
    const src = code(read("src/settings/data-section.ts"));
    expect(src, "没读到 data-section.ts 的真实内容 / 剥过头了").toContain("class DataSection");

    expect(src).toContain('from "../generated/DataPathInfo"');
    expect(src).toContain('from "../generated/DataPathsResponse"');

    // 性质：本地手写 interface 不许回来——**这才是要禁的东西**。
    //
    // **第一版这里禁的是 `invoke<DataPathsResponse>` 那个形态，那条断言本身是错的**：
    // 现在 `DataPathsResponse` 已经是生成的类型，`invoke<生成类型>` 完全正确；
    // 真正的类型化包装层是 C04 的事，C01 明写不建。禁错了东西 = 假红 = 守卫会被人关掉。
    //
    // 审计正向对照：把两个手写 interface 加回来并删掉 import → **本条红而 `tsc` 0 错**
    // ⇒ 这一条是「已接线 / 已拆线」之间唯一的东西。
    expect(src, "本地手写 interface / type 又回来了").not.toMatch(
      /^\s*(export\s+)?(interface|type)\s+DataPath(Info|sResponse)\b/m,
    );

    expect(src).toMatch(/invoke<\s*DataPathsResponse\s*>\(\s*"get_data_paths"\s*\)/);
  });
});
