/**
 * C01（rust-ts-boundary）：**结构性守卫**——生成物必须存在、必须被消费、必须没人手改。
 *
 * **这不是行为测试，也不假装是。** C01 的行为判据是**变异**：
 * 删掉 Rust 的 `DataPathInfo.exists` → 重新导出 → `tsc` 报 6 条错（全部指向
 * `data-section.ts`）；给 `label` 加 `#[serde(rename)]` → `tsc` 报错。
 * 两次都先 `git diff` 确认变异落位、再确认 `cargo test --lib` 538 绿，**然后**才判 tsc 的色
 * ——中间踩了一次「变异编译不过、tsc 却是 0 错」，那个 0 错毫无意义
 * （生成物根本没被重新导出）。全部记在 `.claude/planned-build/rust-ts-boundary/features/C01-*.md`。
 *
 * 本文件只负责防**接线被悄悄拆掉**（有人把手写 interface 加回来、或直接改生成物）。
 *
 * **守卫范围只覆盖 `data-section.ts` 这一个文件。** 不许写成「全仓不许有 `invoke<`」——
 * 其余 118 个命令还没迁，那会假红，**而假红的守卫会被人关掉**（本会话栽过三次）。
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const read = (p: string) => readFileSync(resolve(ROOT, p), "utf8");

/**
 * **剥注释再扫——守卫与断言两侧都要剥。**
 *
 * 本文件第一版没剥，当场自己抓自己红了两次：
 * ① 生成物的 JSDoc 里含有 `sizeBytes: bigint | null` 这串字——因为那是 Rust doc comment 里
 *    解释「不加 `#[ts(optional)]` 会怎样」的原话，被 ts-rs 搬进了 JSDoc；
 * ② `data-section.ts` 的散文里也会出现被禁的形态名。
 * 拿注释当类型判据，是本会话反复栽的形状之一。
 */
function code(src: string): string {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, "") // 块注释 / JSDoc
    .replace(/(^|[^:])\/\/.*$/gm, "$1"); // 行注释（`https://` 不误伤）
}

/** ts-rs v12 写在每个生成文件头部的原话。 */
const TS_RS_HEADER = "generated by [ts-rs]";
const DO_NOT_EDIT = "Do not edit this file manually";

describe("C01 边界生成物", () => {
  it("两个生成文件都在，且都带「不许手改」标记", () => {
    const files = ["src/generated/DataPathInfo.ts", "src/generated/DataPathsResponse.ts"];
    let checked = 0;
    for (const f of files) {
      const src = read(f);
      // 反向自检：真读到内容了，不是空文件在空转
      expect(src.length, `${f} 是空的`).toBeGreaterThan(100);
      expect(src, `${f} 缺 ts-rs 头`).toContain(TS_RS_HEADER);
      expect(src, `${f} 缺「不许手改」`).toContain(DO_NOT_EDIT);
      checked += 1;
    }
    // 计数自检用等号：将来加了第三个生成文件，这里必须红一次以提醒把它纳入守卫
    expect(checked, `期望恰好 2 个生成文件，实得 ${checked}`).toBe(2);
  });

  it("camelCase 真的从 serde 属性传下来了（选 ts-rs 的前提）", () => {
    const info = read("src/generated/DataPathInfo.ts");
    const resp = read("src/generated/DataPathsResponse.ts");
    // Rust 侧是 snake_case + `#[serde(rename_all = "camelCase")]`
    expect(info).toContain("sizeBytes");
    expect(info).not.toContain("size_bytes");
    expect(resp).toContain("monitorDataDir");
    expect(resp).toContain("webviewUserDataDir");
    expect(resp).toContain("profileBackupDirs");
    expect(resp).not.toContain("monitor_data_dir");
  });

  it("带 skip_serializing_if 的字段是 optional，不是 `| null`（否则类型在撒谎）", () => {
    const info = code(read("src/generated/DataPathInfo.ts"));
    // 反向自检：剥完注释还剩类型体（不是剥过头了）
    expect(info, "剥过头了").toContain("export type DataPathInfo");
    // Rust: `#[serde(skip_serializing_if = "Option::is_none")]` + `#[ts(optional)]`
    // ⇒ None 时字段整个缺席 ⇒ TS 侧收到 undefined，绝不会是 null
    expect(info).toContain("sizeBytes?:");
    expect(info, "sizeBytes 不该是必需字段——那声明了一个永不出现的 null").not.toMatch(
      /sizeBytes:\s/,
    );
  });

  it("`u64` 的映射与运行时一致，且是带论证的显式决定而非默认值", () => {
    const info = code(read("src/generated/DataPathInfo.ts"));
    const rust = read("src-tauri/src/data_paths.rs");
    expect(info, "剥过头了").toContain("export type DataPathInfo");

    // 性质：类型必须与运行时一致。Tauri 命令 IPC 走 JSON ⇒ `u64` 到 TS 侧是 number。
    expect(info).toContain("sizeBytes?: number");
    // `ts-rs` 的默认映射是 `bigint`，对 Tauri 的 JSON IPC 是错的 ⇒ 不许回落到默认
    expect(info, "回落到 ts-rs 默认的 bigint 了——那与运行时不一致").not.toContain("bigint");

    // **而且它必须是显式写下的决定，不是碰巧**：Rust 侧要有那个属性 + 上限论证。
    // 少了这一条，将来有人删掉属性、生成物变回 bigint，只有上面两条会红，
    // 而红的原因看起来像「生成物坏了」而不是「有人撤掉了一个带论证的决定」。
    expect(rust, "Rust 侧缺 `type = \"number\"` 的显式声明").toContain('type = "number"');
    expect(rust, "缺上限论证——收窄必须写下为什么安全").toContain("2^53-1");
  });

  it("data-section.ts 的类型来自生成物，本地手写 interface 不许回来", () => {
    const raw = read("src/settings/data-section.ts");
    const src = code(raw);
    // 反向自检：真读到那个文件了，且剥完还剩代码
    expect(src, "没读到 data-section.ts 的真实内容 / 剥过头了").toContain("class DataSection");

    // 性质：两个类型都从生成物 import
    expect(src).toContain('from "../generated/DataPathInfo"');
    expect(src).toContain('from "../generated/DataPathsResponse"');

    // 性质：本地手写 interface 不许回来——**这才是要禁的东西**。
    //
    // **第一版这里禁的是 `invoke<DataPathsResponse>` 那个形态，那条断言本身是错的**：
    // 现在 `DataPathsResponse` 已经是生成的类型，`invoke<生成类型>` 完全正确；
    // 真正的类型化包装层是 C04 的事，C01 明写不建。禁错了东西 = 假红 = 守卫会被人关掉。
    expect(src, "本地手写 interface 又回来了").not.toMatch(
      /^\s*interface\s+DataPath(Info|sResponse)\b/m,
    );

    // 性质：`invoke` 的类型参数必须是那个**被 import 进来的**名字，
    // 而不是本地重新定义的同名类型——上一条已经保证了后者不存在。
    expect(src).toMatch(/invoke<\s*DataPathsResponse\s*>\(\s*"get_data_paths"\s*\)/);
  });
});
